const getImages = {
    'Malaria': require('../Assets/Images/Disease/malaria.jpg'),
    'Fungal infection':require('../Assets/Images/Disease/fungal.jpg'),
    'Allergy':require('../Assets/Images/Disease/Allergy.jpg'),
    'GERD':require('../Assets/Images/Disease/GERD.jpg'),
    'Chronic cholestasis':require('../Assets/Images/Disease/Chroniccholestasis.jpg'),
    'Drug Reaction':require('../Assets/Images/Disease/DrugReaction.jpg'),
    'Peptic ulcer disease':require('../Assets/Images/Disease/Peptic.jpg'),
    'AIDS':require('../Assets/Images/Disease/AIDS.jpg'),
    'Diabetes':require('../Assets/Images/Disease/Diabetes.jpg'),
    'Gastroenteritis':require('../Assets/Images/Disease/Gastroenteritis.jpg'),
    'Bronchial Asthma':require('../Assets/Images/Disease/BronchialAsthma.jpg'),
    'Hypertension':require('../Assets/Images/Disease/Hypertension.jpg'),
    'Migraine':require('../Assets/Images/Disease/Migraine.jpg'),
    'Cervical spondylosis':require('../Assets/Images/Disease/Cervicalspondylosis.jpg'),
    'Paralysis (brain hemorrhage)':require('../Assets/Images/Disease/Paralysis.jpg'),
    'Jaundice':require('../Assets/Images/Disease/Jaundice.jpg'),
    'Chicken pox':require('../Assets/Images/Disease/Chickenpox.jpg'),
    'Dengue':require('../Assets/Images/Disease/Dengue.jpg'),
    'Typhoid':require('../Assets/Images/Disease/Typhoid.jpg'),
    'Hepatitis A':require('../Assets/Images/Disease/HepatitisA.jpg'),
    'Hepatitis B':require('../Assets/Images/Disease/HepatitisB.jpg'),
    'Hepatitis C':require('../Assets/Images/Disease/HepatitisC.jpg'),
    'Hepatitis D':require('../Assets/Images/Disease/HepatitisD.jpg'),
    'Hepatitis E':require('../Assets/Images/Disease/HepatitisE.jpg'),
    'Alcoholic hepatitis':require('../Assets/Images/Disease/Alcoholichepatitis.jpg'),
    'Tuberculosis':require('../Assets/Images/Disease/Tuberculosis.jpg'),
    'Common Cold':require('../Assets/Images/Disease/CommonCold.jpg'),
    'Pneumonia':require('../Assets/Images/Disease/Pneumonia.jpg'),
    'Dimorphic hemmorhoids(piles)':require('../Assets/Images/Disease/piles.jpg'),
    'Heartattack':require('../Assets/Images/Disease/Heartattack.jpg'),
    'Varicoseveins':require('../Assets/Images/Disease/Varicoseveins.jpg'),
    'Hyperthyroidism':require('../Assets/Images/Disease/Hyperthyroidism.jpg'),
    'Hypoglycemia':require('../Assets/Images/Disease/Hypoglycemia.jpg'),
    'Osteoarthristis':require('../Assets/Images/Disease/Osteoarthristis.jpg'),
    'Arthritis':require('../Assets/Images/Disease/Arthritis.jpg'),
    '(vertigo) Paroymsal  Positional Vertigo':require('../Assets/Images/Disease/Vertigo.jpg'),
    'Acne':require('../Assets/Images/Disease/Acne.jpg'),
    'Urinary tract infection':require('../Assets/Images/Disease/Allergy.jpg'),
    'Psoriasis':require('../Assets/Images/Disease/Psoriasis.jpg'),
    'Impetigo':require('../Assets/Images/Disease/Allergy.jpg')
};

export function GetImage(name) {
    return getImages[name];
  }